version: '3.8'

services:
  db:
    image: postgres:14
    container_name: fit_tribe_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-fit_tribe}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Uncomment and configure if Redis is needed for caching or session management
  # redis:
  #   image: redis:alpine
  #   container_name: fit_tribe_redis
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data: {}